### PR TITLE
MultiLangDaemon: Make shutdown grace configurable

### PR DESCRIPTION
**Pull request by AlexCharlton**
The shutdown grace added to the MultiLangDaemon in 1.7.6 proved to be essential for my application, but the hard-coded 5 second grace is too harsh for my needs. This adds a configuration parameter for the grace period.

### CODE REVIEW

**Comment by pfifer** [comment]
Please confirm that we can use, modify, copy, and redistribute this contribution.

Thanks.

**Comment by AlexCharlton** [comment]
You may use, modify, copy, and redistribute this contribution.

**Comment by pfifer** [comment]
One more question: Is the change coming from yourself, or from Instacart?

**Comment by jackdempsey** [comment]
@pfifer Can you share some info on the context behind the question? (why it matters, what it means, etc). Thanks

**Comment by pfifer** [comment]
If it's coming from Instacart we just need to confirm that Alex has authority from Instacart to contribute the change to us under the same language:
> Please confirm that we can use, modify, copy, and redistribute this contribution.

I'm sorry for all the extra steps.   

Also can you let me know which of the multi-lang daemon clients use.

**Comment by jackdempsey** [comment]
Hey pfifer, thanks and no worries. What do you need to confirm he has the authority? (He's on my team here and I can confirm he does)

**Comment by AlexCharlton** [comment]
Yes @pfifer, these changes are coming from Instacart. I can also confirm that @jackdempsey is my manager, and that I have it from the highest authority that you can use, modify, copy and redistribute this contribution :)

Sorry, I'm not sure what you mean by:

> Also can you let me know which of the multi-lang daemon clients use.

**Comment by pfifer** [comment]
I need to update the multi-lang clients to use the newer version of the KCL, and was curious which language you're were using.  

I do plan to include this change in the upcoming release.

**Comment by AlexCharlton** [comment]
Ah, I see. We're using Ruby, but not https://github.com/awslabs/amazon-kinesis-client-ruby . We've written our own client library, which we'll probably open-source before long. LKM if yo'd like to be notified if we do.

Thanks!

**Pull request merged**
