### PR TITLE
Remove dependency from aws sdk v1

### PR DESCRIPTION
**Pull request by abhit17**
## *Description of changes:*

Removing dependency from aws sdk v1 for multilang deamon. KCL is already updated.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

## *Testing*

1. Tested by running `mvn verify`
2. Tested by running python kcl on this updated multi lang deamon.

Logs for mvn verify

```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Amazon Kinesis Client Library 2.5.1:
[INFO]
[INFO] Amazon Kinesis Client Library ...................... SUCCESS [  2.145 s]
[INFO] Amazon Kinesis Client Library for Java ............. SUCCESS [15:07 min]
[INFO] amazon-kinesis-client-multilang .................... SUCCESS [ 12.868 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  15:23 min
[INFO] Finished at: 2023-07-06T19:28:11-07:00
[INFO] ------------------------------------------------------------------------
```

### CODE REVIEW

**Review by chenylee-aws — COMMENTED** [review]
I see there are still some reference to the V1 package (com.amazonaws) for example [here](https://github.com/awslabs/amazon-kinesis-client/blob/master/amazon-kinesis-client-multilang/src/main/java/software/amazon/kinesis/multilang/config/AWSCredentialsProviderPropertyValueDecoder.java#L22-L23). We might want to clean them up as well but I don't know if this will break support for people who are still using SDK V1 in other language through multilang.

**Comment by stair-aws** [comment]
FYI, related issue: https://github.com/awslabs/amazon-kinesis-client/issues/1161

**Comment by junyuc25** [comment]
Hi @stair-aws , it looks like the one of the modules is transitively depending on SDK v1, as shown below:
`mvn dependency:tree -Dincludes="com.amazonaws:*"`
```
[INFO] software.amazon.kinesis:amazon-kinesis-client:jar:2.5.1
[INFO] \- software.amazon.glue:schema-registry-serde:jar:1.1.14:compile
[INFO]    \- com.amazonaws:aws-java-sdk-sts:jar:1.12.151:compile
[INFO]       +- com.amazonaws:aws-java-sdk-core:jar:1.12.151:compile
[INFO]       \- com.amazonaws:jmespath-java:jar:1.12.151:compile

```
Please correct me if I'm wrong. It seems to me that, without first upgrading `schema-registry-serde`, KCL could not be fully migrated to SDK v2.

**Comment by stair-aws** [comment]
> [junyuc25@] It seems to me that, without first upgrading `schema-registry-serde`, KCL could not be fully migrated to SDK v2.

Mostly agree, yet disagree on "first". We should be able to revise KCL independent from Glue -- and revbump serde later -- yet both will need updates to holistically remove SDK v1. This transitive inclusion of SDK v1 explains [chenylee-aws@'s observation](https://github.com/awslabs/amazon-kinesis-client/pull/1163#pullrequestreview-1519176299).

**Comment by stair-aws** [comment]
While we can modify the KCL code to not depend on SDKv1, we likely cannot remove the dependency on SDKv1 -- direct _or_ transitive -- outside of a major release. Multilang customers may exist that utilize [AWSCredentialsProviders](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/auth/AWSCredentialsProvider.html) via properties file `AWSCredentialsProvider = <SDKv1 class name>` inclusion (see [sample.properties](https://github.com/awslabs/amazon-kinesis-client-python/blob/master/samples/sample.properties#L26)).

[AWSCredentialsProviderPropertyValueDecoder](https://github.com/awslabs/amazon-kinesis-client/blob/master/amazon-kinesis-client-multilang/src/main/java/software/amazon/kinesis/multilang/config/AWSCredentialsProviderPropertyValueDecoder.java#L144) maps a simple class name (e.g., `STSAssumeRoleSessionCredentialsProvider`) to its fully-qualified SDKv1 class.

**Comment by junyuc25** [comment]
Hi @stair-aws , can we prepare for a major release for the SDK upgrade? And how much efforts will it take to release a major version?

**Comment by stair-aws** [comment]
> can we prepare for a major release for the SDK upgrade? And how much efforts will it take to release a major version?

@junyuc25 Salut! Let's bring this conversation internally so we can discuss in depth. I responded to your DM and commented on our team ticket. Thanks!

**Pull request closed without merging**
