### PR TITLE
only depend on aws code that is actually needed

### PR DESCRIPTION
**Pull request by chadselph**
mvn dependency:tree Before:

```
[INFO] com.amazonaws:amazon-kinesis-client:jar:1.2.1
[INFO] \- com.amazonaws:aws-java-sdk:jar:1.9.16:compile
[INFO]    +- com.amazonaws:aws-java-sdk-support:jar:1.9.16:compile
[INFO]    +- com.amazonaws:aws-java-sdk-simpledb:jar:1.9.16:compile
[INFO]    +- com.amazonaws:aws-java-sdk-simpleworkflow:jar:1.9.16:compile
[INFO]    +- com.amazonaws:aws-java-sdk-storagegateway:jar:1.9.16:compile
[INFO]    +- com.amazonaws:aws-java-sdk-route53:jar:1.9.16:compile
[INFO]    +- com.amazonaws:aws-java-sdk-s3:jar:1.9.16:compile
[INFO]    +- com.amazonaws:aws-java-sdk-importexport:jar:1.9.16:compile
[INFO]    +- com.amazonaws:aws-java-sdk-sts:jar:1.9.16:compile
[INFO]    +- com.amazonaws:aws-java-sdk-sqs:jar:1.9.16:compile
[INFO]    +- com.amazonaws:aws-java-sdk-rds:jar:1.9.16:compile
[INFO]    +- com.amazonaws:aws-java-sdk-redshift:jar:1.9.16:compile
[INFO]    +- com.amazonaws:aws-java-sdk-elasticbeanstalk:jar:1.9.16:compile
[INFO]    +- com.amazonaws:aws-java-sdk-glacier:jar:1.9.16:compile
[INFO]    +- com.amazonaws:aws-java-sdk-iam:jar:1.9.16:compile
[INFO]    +- com.amazonaws:aws-java-sdk-datapipeline:jar:1.9.16:compile
[INFO]    +- com.amazonaws:aws-java-sdk-elasticloadbalancing:jar:1.9.16:compile
[INFO]    +- com.amazonaws:aws-java-sdk-emr:jar:1.9.16:compile
[INFO]    +- com.amazonaws:aws-java-sdk-elasticache:jar:1.9.16:compile
[INFO]    +- com.amazonaws:aws-java-sdk-elastictranscoder:jar:1.9.16:compile
[INFO]    +- com.amazonaws:aws-java-sdk-ec2:jar:1.9.16:compile
[INFO]    +- com.amazonaws:aws-java-sdk-dynamodb:jar:1.9.16:compile
[INFO]    +- com.amazonaws:aws-java-sdk-sns:jar:1.9.16:compile
[INFO]    +- com.amazonaws:aws-java-sdk-cloudtrail:jar:1.9.16:compile
[INFO]    +- com.amazonaws:aws-java-sdk-cloudwatch:jar:1.9.16:compile
[INFO]    +- com.amazonaws:aws-java-sdk-logs:jar:1.9.16:compile
[INFO]    +- com.amazonaws:aws-java-sdk-cognitoidentity:jar:1.9.16:compile
[INFO]    +- com.amazonaws:aws-java-sdk-cognitosync:jar:1.9.16:compile
[INFO]    +- com.amazonaws:aws-java-sdk-directconnect:jar:1.9.16:compile
[INFO]    +- com.amazonaws:aws-java-sdk-cloudformation:jar:1.9.16:compile
[INFO]    +- com.amazonaws:aws-java-sdk-cloudfront:jar:1.9.16:compile
[INFO]    +- com.amazonaws:aws-java-sdk-kinesis:jar:1.9.16:compile
[INFO]    +- com.amazonaws:aws-java-sdk-opsworks:jar:1.9.16:compile
[INFO]    +- com.amazonaws:aws-java-sdk-ses:jar:1.9.16:compile
[INFO]    +- com.amazonaws:aws-java-sdk-autoscaling:jar:1.9.16:compile
[INFO]    +- com.amazonaws:aws-java-sdk-cloudsearch:jar:1.9.16:compile
[INFO]    +- com.amazonaws:aws-java-sdk-cloudwatchmetrics:jar:1.9.16:compile
[INFO]    +- com.amazonaws:aws-java-sdk-swf-libraries:jar:1.9.16:compile
[INFO]    +- com.amazonaws:aws-java-sdk-codedeploy:jar:1.9.16:compile
[INFO]    +- com.amazonaws:aws-java-sdk-kms:jar:1.9.16:compile
[INFO]    +- com.amazonaws:aws-java-sdk-config:jar:1.9.16:compile
[INFO]    +- com.amazonaws:aws-java-sdk-lambda:jar:1.9.16:compile
[INFO]    +- com.amazonaws:aws-java-sdk-ecs:jar:1.9.16:compile
[INFO]    +- com.amazonaws:aws-java-sdk-cloudhsm:jar:1.9.16:compile
[INFO]    \- com.amazonaws:aws-java-sdk-core:jar:1.9.16:compile
[INFO]       +- commons-logging:commons-logging:jar:1.1.3:compile
[INFO]       +- org.apache.httpcomponents:httpclient:jar:4.3.4:compile
[INFO]       |  +- org.apache.httpcomponents:httpcore:jar:4.3.2:compile
[INFO]       |  \- commons-codec:commons-codec:jar:1.6:compile
[INFO]       +- com.fasterxml.jackson.core:jackson-databind:jar:2.3.2:compile
[INFO]       |  +- com.fasterxml.jackson.core:jackson-annotations:jar:2.3.0:compile
[INFO]       |  \- com.fasterxml.jackson.core:jackson-core:jar:2.3.2:compile
[INFO]       \- joda-time:joda-time:jar:2.7:compile (version selected from constraint [2.2,))
```

after:

```
[INFO] com.amazonaws:amazon-kinesis-client:jar:1.2.1
[INFO] +- com.amazonaws:aws-java-sdk-core:jar:1.9.16:compile
[INFO] |  +- commons-logging:commons-logging:jar:1.1.3:compile
[INFO] |  +- org.apache.httpcomponents:httpclient:jar:4.3.4:compile
[INFO] |  |  +- org.apache.httpcomponents:httpcore:jar:4.3.2:compile
[INFO] |  |  \- commons-codec:commons-codec:jar:1.6:compile
[INFO] |  +- com.fasterxml.jackson.core:jackson-databind:jar:2.3.2:compile
[INFO] |  |  +- com.fasterxml.jackson.core:jackson-annotations:jar:2.3.0:compile
[INFO] |  |  \- com.fasterxml.jackson.core:jackson-core:jar:2.3.2:compile
[INFO] |  \- joda-time:joda-time:jar:2.7:compile (version selected from constraint [2.2,))
[INFO] +- com.amazonaws:aws-java-sdk-dynamodb:jar:1.9.16:compile
[INFO] |  \- com.amazonaws:aws-java-sdk-s3:jar:1.9.16:compile
[INFO] |     \- com.amazonaws:aws-java-sdk-kms:jar:1.9.16:compile
[INFO] +- com.amazonaws:aws-java-sdk-kinesis:jar:1.9.16:compile
[INFO] \- com.amazonaws:aws-java-sdk-cloudwatch:jar:1.9.16:compile
[INFO] ------------------------------------------------------------------------
```

For people deploying applications as a single jar, this is a nice savings.

### CODE REVIEW

**Comment by jplock** [comment]
+1

**Comment by pauldraper** [comment]
+1 No-brainer

**Comment by pebo** [comment]
+1

**Comment by manango** [comment]
@chadselph thank you for your feedback. KCL 1.5.0 addresses this issue.

**Comment by chadselph** [comment]
thanks!

**Pull request closed without merging**
