### PR TITLE
Fix preparing a checkpoint at SHARD_END (Replaced with #301)

### PR DESCRIPTION
**Pull request by wdbaruni**
Fix IllegalArgumentException: Sequence number must be numeric, when preparing a checkpoint at SHARD_END.

This also fixes calling checkpoint(SHARD_END)

### CODE REVIEW

**Comment by wdbaruni** [comment]
#236

**Comment by pfifer** [comment]
Could you rebase your branch on master to clean up the commit history?

**Comment by wdbaruni** [comment]
Created a new PR #301 with a rebased branch

**Comment by pfifer** [comment]
Closed in favor of #301

**Pull request closed without merging**
