### PR TITLE
logging method entry/exit for shard syncer to help debug races faster

### PR DESCRIPTION
**Pull request by aggarwal**
Logging method entry/exit for shard syncer to help debug races faster.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by sahilpalvia** [comment]
Have you tried enabling debug logs on the ShardSyncer class? The logs just seem to be marking the entry and exits of the methods.

**Comment by aggarwal** [comment]
The goal of this change is to make it easier to reconstruct timelines of race conditions that lead to unexpected behavior. Customers don't generally enable debug logging by default, and we'd like to have sufficient data from the very first occurrence of an issue. Since the purpose is solely to reconstruct a timeline, we don't need to log any additional shard information.

**Comment by sahilpalvia** [comment]
Could you elaborate on the race conditions? All the methods that are called from outside the class are synchronized and shouldn't be causing race conditions.

**Comment by aggarwal** [comment]
Sure, the races we're concerned about are generally across hosts. So synchronization within a process does not eliminate the possibility of a race between two concurrently executing shard syncs.

An example:
T0 - Host A starts executing ShardSync
T1 - Host A experiences a GC pause shortly after completing calls to DescribeStream, but before creating any leases. The DescribeStream calls exposed Shard-A without an ending shard sequence number, meaning it is still open.
T2 - Host B starts executing ShardSync, creates new leases, and deletes SHARD_END leases for which child leases have been created. Let's say one such deleted lease is for Shard-A.
T3 - Host A now unpauses after GC, and now determines that it needs to create a lease for Shard-A.

The specific race condition is not important in the above example. I'm simply illustrating how races are possible.

**Comment by sahilpalvia** [comment]
Thanks for that scenairo. But I don't think it should be an issue, as the lease can only be deleted by the ShardConsumer which holds the lease and has processed it to `SHARD_END`. Describing or Listing shards will not delete the lease. The lease will also be deleted only when the children shards have started processing and have checked pointed with a value other than `SHARD_END`.

**Comment by aggarwal** [comment]
This statement is incorrect: "as the lease can only be deleted by the ShardConsumer which holds the lease". See this code: https://github.com/awslabs/amazon-kinesis-client/blob/v1.x/src/main/java/com/amazonaws/services/kinesis/clientlibrary/lib/worker/ShardSyncer.java#L144-L150

Any worker can delete leases regardless of lease ownership.

**Comment by sahilpalvia** [comment]
Good catch, maybe that could be a better solution to force deletion done by the lease owner. That could help avoid this race condition.

**Comment by aggarwal** [comment]
DDB Streams is going to inject it's own implementation of ShardSyncer, so this PR is no longer relevant.

**Pull request closed without merging**
