### PR TITLE
Configurable DynamoDB BillingMode

### PR DESCRIPTION
**Pull request by etspaceman**
*Issue #, if available:* #489 

*Description of changes:* Adds BillingMode to the LeaseManagementConfig so that users can leveraged the pay-per-request upon table creation

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by etspaceman** [comment]
Seems the CI failed once due to issues unrelated to the code changes.

**Comment by Cory-Bradshaw** [comment]
Thanks for working on this. Let me take a look and confirm default behavior works as expected and there aren't validation problems when providing both PAY_PER_REQUEST and provisioning levels.

**Comment by etspaceman** [comment]
Thanks, sounds good. I can update this with any needed changes.

**Comment by Cory-Bradshaw** [comment]
Found a bug, submitting a fix. DDB table cannot be set to PAY_PER_REQUEST while specifying the provisioning levels. 

Adding unit and integration tests as well...

**Pull request merged**
