### PR TITLE
Preparation for v2.4.0

### PR DESCRIPTION
**Pull request by blacktooth**
*Description of changes:*

`mvn clean install -DskipItTests` was successful.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by namanksrivastava — APPROVED** [review]
lgtm. Will wait for Sachin's approval before merge.

**Comment by shanmsac** [comment]
@blacktooth why update minor version? release only has dependency updates

**Comment by blacktooth** [comment]
> 

The dependency update adds support for Protobuf data format in KCL. This is a new feature.

**Review by shanmsac — APPROVED** [review]
lgtm

**Pull request merged**
