### PR TITLE
Create table resilience

### PR DESCRIPTION
**Pull request by avram**
This breaks the dependency of worker start on the CreateTable API in DynamoDB, which prevented KCL workers from starting during the us-east-1 DynamoDB outage today.

### CODE REVIEW

**Comment by samcday** [comment]
Can we get this reviewed and merged please? We manage our DynamoDB table separately to our KCL app, and we use very strict IAM roles for access to the table. It's kinda silly that we have to grant the KCL app permission to create a table we know already exists.

**Comment by Jackyjjc** [comment]
sorry for pulling you in @pfifer, I saw you were being active on the other PRs. I work on the same team as Sam and we really want this PR to get merged so that we don't have the infrastructure overhead of managing extra IAM roles.

**Comment by pfifer** [comment]
A version of this is already merged: https://github.com/awslabs/amazon-kinesis-client/commit/8fc5dd5862b5daf777fad06c66d2a948e5caf9ad

This PR, and [Fix #36 Avoid failure on start due to CreateTable](https://github.com/awslabs/amazon-kinesis-client/pull/67) are very similar.

I'm starting the process of release to Maven today, and hope to have v1.6.5 out soon.

**Comment by pfifer** [comment]
The change is committed, and will be released to Maven soon.

**Pull request closed without merging**
