### PR TITLE
Allow specifying a custom LeaseManager in Worker.Builder with tests

### PR DESCRIPTION
**Pull request by felipegasparini**
Continuing the work started on PR: 
https://github.com/awslabs/amazon-kinesis-client/pull/255

(sorry for creating a new PR)

Added tests as requested.

### CODE REVIEW

**Comment by pfifer** [comment]
Thanks for providing this.  I'm looking at the changes, but don't have an ETA right now.

**Comment by felipegasparini** [comment]
Ok! Let me know if you need something else.
My use case is similar to the others one that requested this change: Be able to use another implementation of LeaseManager (baked by another datastore).

If you have another solution to solve this problem that makes more sense for the project, let me know.

**Comment by pfifer** [comment]
I just need everyone to please confirm that we can use, modify, copy, and redistribute this contribution. 

Thanks

**Comment by felipegasparini** [comment]
Sure! How can I do that?
Do you have a contributors license agreement or something similar?

**Comment by pfifer** [comment]
No CLA is required, just need you to agree for us to distribute this.  Did you based the changes off of @johnsonwj changes?  If that's the case I need them to also agree to allow us to distribute the changes.

**Comment by felipegasparini** [comment]
From my side there is no problem at all.
And yes, I actually just continued @johnsonwj contribution. So let's wait for him.
Thanks!

**Comment by johnsonwj** [comment]
Apologies for not seeing this earlier! You have my permission to use/modify/copy/redistribute my contribution!

**Comment by felipegasparini** [comment]
You also have my permission to use/modify/copy/redistribute my contribution.

**Comment by felipegasparini** [comment]
Thanks, @pfifer !

**Pull request merged**
