### PR TITLE
Add proxy support

### PR DESCRIPTION
**Pull request by mscharp**
Read proxy info from application.properties file first,
then java system settings, and finally from ENV vars.

*Issue #, if available:*
#23
*Description of changes:*
Basic proxy support for KCL

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by joshua-ramer** [comment]
I need this as well. Who doesn't have a proxy? Please merge this asap so we can actually use the KCL.

**Comment by pfifer** [comment]
This was submitted before the release of 2.0.0.  If you want this in the 1.9.x version can you change the source branch to v1.x.

**Comment by mscharp** [comment]
Yup, this was submitted before the 2.0 release.  I had hoped this would have been merged prior to the release so that it would have been included...

I will create a new PR to the 1.x line, and hope someone takes the time to bring it forward.

**Comment by pfifer** [comment]
Closing this in favor of #365

**Pull request closed without merging**
