### PR TITLE
Make use of Java 8 to simplify `computeLeaseCounts()`

### PR DESCRIPTION
**Pull request by rtyley**
It's possible to remove quite a few lines of code from the method using Java 8 features (`groupingBy` Collector, etc).

Java 8 is the minimum supported version of the KCL since PR https://github.com/awslabs/amazon-kinesis-client/pull/176 was merged in July 2017.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by joshua-kim — APPROVED** [review]
LGTM, thanks for the invent-and-simplify.

**Comment by rtyley** [comment]
Many thanks @joshua-kim! I also have a couple of other open PRs, if you have time to review them:

* Fairly small: https://github.com/awslabs/amazon-kinesis-client/pull/846
* Larger: https://github.com/awslabs/amazon-kinesis-client/pull/848

**Comment by joshua-kim** [comment]
I reviewed the smaller of the two, #848 which aims to optimize lease convergence time sounds promising but is a change to a rather critical part of KCL. Don't have an ETA of when I'll be able to look into/test it currently.

**Comment by rtyley** [comment]
Sure- thanks for taking a quick look anyway, and of course for merging the logging fix.

**Pull request merged**
