### PR TITLE
Allow DynamoDB table name to be specified

### PR DESCRIPTION
**Pull request by samcday**

### CODE REVIEW

**Comment by dlsniper** [comment]
@samcday would you like to update the PR to fix the conflicts? If not, I can open a separate one but I'd rather have this one merged than have two different PRs solving the same thing.

**Comment by samcday** [comment]
@dlsniper sorted! Pesky formatting changes in upstream ;)

**Comment by pfifer** [comment]
I've started the process of merging the pull request internally.  Unfortunately I had to delay merging this for the 1.6.4 release.  I do plan to have this merged, and released in the near future.

**Comment by pfifer** [comment]
Please confirm that we can use, modify, copy, and redistribute this contribution. After I get the confirmations I can begin the release process.

Thanks.

**Comment by samcday** [comment]
Confirmed.

**Comment by pfifer** [comment]
This change is committed, and will be released to Maven soon.

**Pull request closed without merging**
